services:
  simplemicroservice:
    image: simplemicroservice
    build:
      context: .
      dockerfile: Dockerfile

  payment.api:
    image: payment.api
    build:
      context: .
      dockerfile: Payment.Api/Dockerfile

  payment.application:
    image: payment.application
    build:
      context: .
      dockerfile: Payment.Application/Dockerfile

  payment.domain:
    image: payment.domain
    build:
      context: .
      dockerfile: Payment.Domain/Dockerfile

  payment.infrastructure:
    image: payment.infrastructure
    build:
      context: .
      dockerfile: Payment.Infrastructure/Dockerfile

  gateway.api:
    image: gateway.api
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile

  gateway.application:
    image: gateway.application
    build:
      context: .
      dockerfile: Gateway.Application/Dockerfile

  gateway.domain:
    image: gateway.domain
    build:
      context: .
      dockerfile: Gateway.Domain/Dockerfile

  gateway.infrastructure:
    image: gateway.infrastructure
    build:
      context: .
      dockerfile: Gateway.Infrastructure/Dockerfile

