version: '3.9'

services:
  # ===========================
  # 🐘 PostgreSQL Database
  # ===========================
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456Aa@
      POSTGRES_DB: paymentdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ===========================
  # 🐇 RabbitMQ
  # ===========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # ===========================
  # 💳 Payment Service
  # ===========================
  payment-service:
    build:
      context: ./Services/Payment
      dockerfile: Dockerfile
    container_name: payment-service
    depends_on:
      - postgres
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=paymentdb;Username=admin;Password=123456Aa@"
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
    ports:
      - "5001:8080"

  # ===========================
  # 🌐 Gateway Service
  # ===========================
  gateway-service:
    build:
      context: ./Services/Gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    depends_on:
      - payment-service
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PaymentService__BaseUrl: "http://payment-service:8080"
    ports:
      - "5002:8081"

  # ===========================
  # 🔔 Notification Service
  # ===========================
  notification-service:
    build:
      context: ./Services/Notification
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
    ports:
      - "5003:8082"

volumes:
  pgdata:
